### ISSUE TITLE
Outils : GDB

### ISSUE THREAD

**Issue by Edgar-Gevorgyan** [obonaventure/SystemesInformatiques#124]
Le lien de l'archive à télécharger : src/gdb.c contient peut-ếtre une erreur. Après avoir téléchargé, il y a simplement un fichier gdb.c avec une fonction main, iter et calc sans Makefile :
[gdb.txt](https://github.com/obonaventure/SystemesInformatiques/files/1946081/gdb.txt)

**Comment by obonaventure** [comment]
Resolu par https://github.com/obonaventure/SystemesInformatiques/commit/cfb9a7971d7ba128cc179f9acab336211bd67296
