### ISSUE TITLE
code blocks: lines starting with # are not visible

### ISSUE THREAD

**Issue by matttbe** [obonaventure/SystemesInformatiques#58]
Bonjour,

Il semblerait que les lignes commençant par un dièse (ex: `#include <stdlio.h>`) dans les exercices ne sont pas visible dans les fichiers HTML produits. C'est par exemple visible à la question 3: http://sites.uclouvain.be/SystInfo/qcm/Mission-1-qcm.html

Je suppose qu'un simple ajout de backslash peut suffire mais je ne connais pas plus que ça RestructuredText et je n'ai pas testé.

**Comment by obonaventure** [comment]
J'ai migré vers l'extension mcq de sphinx utilisée pour le cours de réseaux et cela devrait résoudre le problème, mais cela m'oblige à réécrire tous les QCM

**Comment by matttbe** [comment]
En regardant le code source généré, il semblerait qu'il ne gère pas le code de la même manière que dans dans la partie de théorie. Du coup, il va utiliser, pour du code de préprocesseur, les classes `comment` et `preproc` au lieu de `cp`. Hors, toutes les classes `comment` sont cachées au premier affichage.

Dans la Pull Request #62, si on utilise des classes `comment` et `preproc` en même temps, le texte ne sera pas caché.

Par contre, le mieux serait de générer le code HTML de la même manière que dans la théorie mais ce n'est peut-être pas possible sans devoir utiliser l'extension mcq de Sphinx.

**Comment by obonaventure** [comment]
C'est probablement lié à l'utilisation de la directive code:: dans l'ancien restructured text et code-block dans sphinx, je vais tout migrer à sphinx dans les prochaines semaines et cela devrait régler le problème (j'espère)
