### ISSUE TITLE
Solutions QCM 5

### ISSUE THREAD

**Issue by sCreami** [obonaventure/SystemesInformatiques#77]
Bonjour,

J'ai des doutes vis-à-vis d'une question du QCM de la semaine 5. Je pense que la question pourrait être imprécise.
La question demande de choisir laquelle des fonctions proposées ne modifie pas la valeur de `errno`

 Une proposition définie comme correcte est `malloc()`
Dans le manuel annexé au site, il est écrit que selon le standard Unix98, `malloc` change la valeur de `errno`.

![Manuel malloc](http://i.imgur.com/a0hEZwv.png)

Peut-être que ce comportement pourrait être annoté à coté de "Voir le manuel"

 Une autre proposition définie comme incorrecte est `pthread_join()`
Comme on peut lire dans la définition du standard IEEE Std 1003.1 édition 2013 collée ci-dessous.
À ce jour, le résultat d'une erreur d'exécution de `pthread_join()` est toujours indéfini. Nous n'avons aucune certitude que `errno` va changer.

![Norme IEEE 1003.1](http://i.imgur.com/wyg8aek.png)

http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_join.html

**Comment by obonaventure** [comment]
Merci pour cette analyse détaillée. J'ai mis à jour le code source sur le git.
